### ISSUE TITLE
`git push origin main` Starts with uppercase

### ISSUE THREAD

**Issue by vitorgalvao** [antoniorodr/Git-snippets-for-Alfred#1]
Should start with lowercase.

<img width="684" alt="image" src="https://github.com/user-attachments/assets/df2b6b71-28eb-4488-8cb7-a7782fcf5fa1">

**Comment by antoniorodr** [comment]
Hi @vitorgalvao!

Thanks for using the snippets. 

You are right! Good catch. I will fix for the next release.

**Comment by antoniorodr** [comment]
Hi @vitorgalvao again!

Could you download the last release and check if the typo is gone?

Thanks in advance!

**Comment by vitorgalvao** [comment]
Oh, I actually use my own shell aliases and functions that I’ve developed over the years and are completely ingrained in my muscle memory and work exactly how I want, to the point it’d be hard for me to switch. But I think your idea of a collection of Git snippets has merit and wanted to check out what you included.

It does look good now. Thumbs up on the quick fix and collection!

**Comment by antoniorodr** [comment]
Thanks a lot @vitorgalvao!

I completely understand. I'm quite new in the programming world, but I thought it could be nice to have a git snippets as an alternative to git aliases. They are short, easy to remember (and check) and can be easily synchronised between computers.

I will add more snippets tho, but I think I covered the most used by now.

**Comment by vitorgalvao** [comment]
> I thought it could be nice to have a git snippets as an alternative to git aliases. They are short, easy to remember (and check) and can be easily synchronised between computers.

Completely agreed!
