### ISSUE TITLE
Suggestion: Improve items which require further input with {cursor}

### ISSUE THREAD

**Issue by vitorgalvao** [antoniorodr/Git-snippets-for-Alfred#2]
There are some items in the snippets which require further user input and are thus incomplete. One example is `;;cam` which expands to `git commit -a -m "`, requiring the user to type the message *and add a closing `"`*. One way you can improve it is with `{cursor}`, as in `git commit -a -m "{cursor}"`. That will add everything, *including the closing `"`* and place the user’s cursor right where it needs to be, between the quotes.

**Comment by antoniorodr** [comment]
Hi @vitorgalvao !

I will definitely look into it. 

I've maybe some time tomorrow to add your improves and release a new version with them 😊

You can be a contributor if you want too, or add this little project to Alfred's "favorite snippets" 😜

Thanks a lot!

**Comment by antoniorodr** [comment]
Snippets updated now! You can try the new version to see if it working as intended now.

Thanks!
