### ISSUE TITLE
Are the backslashed intended?

### ISSUE THREAD

**Issue by vitorgalvao** [antoniorodr/Git-snippets-for-Alfred#3]
`;;ls` and `;;ll` both have backslashes in them. Are they intended? They are included in the output but doesn’t look like they’re doing anything.

**Comment by antoniorodr** [comment]
Hello @vitorgalvao !!

Thanks a lot again for contributing to this little project. 

I think they are intended, but only as something aesthetic. I got the aliases from her: https://www.durdn.com/blog/2012/11/22/must-have-git-aliases-advanced-examples/

Thanks!

**Comment by vitorgalvao** [comment]
Ah, that actually shows they are *not* intended. See, those commands are meant to be added to `~/.config/git` under `[alias]`, and the backslashes are needed in there. But if you’re “typing” them directly, as is the case with snippets, they’re not.

You can verify this by running your snippets and comparing them to the ones on that page. Yours show backslashes but the screenshots on the page do not. If you add those commands to your git config (as opposed to snippets), you’ll also see they produce different behaviour.

**Comment by antoniorodr** [comment]
@vitorgalvao 

Thanks for the clarification!

I will link into it so soon I can. Maybe tomorrow 😊👍

**Comment by antoniorodr** [comment]
Snippets updated now! You can try the new version to see if it working as intended now.

Thanks!
